### ISSUE TITLE
Incorrect handling of non-paired start-end messages

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/otii-consumption-analysis#2]
The following scenario can be observed:
```
START1
STOP
START2
STOP
START1
STOP
```
if start message is defined as `START1` and end message as `STOP`, then the code will currently recognize 2 start conditions and 3 end conditions in this case, while it should form an array of two start conditions followed with the associated end (first one that appears)

**Comment by TjazVracko** [comment]
START and STOP messages should be unique pairs.
